
name: Leo_18.06_x64

on: 
  release:
    types: [published]

  push:
  #  branches: 
  #    - master
      paths:
      - '.github/workflows/Leo_18.06_x64.yml'
  #schedule:
  #  - cron: 0 8 * * 5
  
  watch:
    types: [started]

env:
  REPO_URL: https://github.com/ycg31/openwrt18.06
  REPO_BRANCH: master
  CONFIG_FILE: Leo3.config
  DIY_SH: leo222.sh
  SSH_ACTIONS: false
  UPLOAD_IPK: true
  UPLOAD_FIRMWARE_ALL: true
  UPLOAD_FIRMWARE_UEFI: true
  UPLOAD_FIRMWARE_COMBINED: true
  UPLOAD_COWTRANSFER: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          # sudo mkdir -p -m 777 /mnt/openwrt/bin /mnt/openwrt/build_dir/host /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir
          # ln -s /mnt/openwrt/bin ./bin
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/host ./build_dir/host
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/hostpkg ./build_dir/hostpkg
          # ln -s /mnt/openwrt/dl ./dl
          # ln -s /mnt/openwrt/feeds ./feeds
          # ln -s /mnt/openwrt/staging_dir ./staging_dir
          df -h
          
    - name: Clone source code
      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt

    - name: 解压包
      working-directory: ./openwrt/package/diy
      run: |
         tar   xvJf  luci-app-docker.tar.xz
         tar   xvJf  luci-app-koolddns.tar.xz
         tar   xvJf  luci-app-rclone.tar.xz
         tar   xvJf  autocore.tar.xz
         tar   xvJf  luci-app-nps.tar.xz
         tar   xvJf  luci-app-adbyby-plus.tar.xz
    
    - name: Import external feeds
      working-directory: ./openwrt/package/diy
      run: |
         git clone -b lean  https://github.com/Sweet-Fairy/luci-app-ssr-plus-Jo package/luci-app-ssr-plus-lean    
         git clone https://github.com/ycg31/luci-app-vssr
         git clone https://github.com/ycg31/luci-app-openwrt_firmware
         git clone https://github.com/Sweet-Fairy/openwrt-package
         git clone https://github.com/frainzy1477/luci-app-clash.git
         git clone https://github.com/vernesong/OpenClash.git
    - name: 删除冲突文件
      working-directory: ./openwrt
      run: |  
         rm   -rfv  package/my/luci-app-openclash 
         rm   -rfv  package/my/luci-app-clash
         rm   -rfv  package/my/luci-app-openwrt_firmwareR
         
    - name: Update & Install feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
           
    - name: Configuration Customization
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x ./$DIY_SH && ./$DIY_SH
        cd openwrt && make defconfig
        
    - name: Download package
      working-directory: ./openwrt
      run: |
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        
    - name: Multi-thread compile
      working-directory: ./openwrt
      run: |
          echo -e "$(nproc) thread build."
          make -j$(nproc) V=s
    - name: Single-thread compile
      working-directory: ./openwrt
      if: failure()
      run: |
          make -j1 V=s      
    
    - name: Assemble combined
      run: |
          rm -rf ./combined/
          mkdir -p ./combined/
          find openwrt/bin/targets/ -name "*sysupgrade*bin*" | xargs -i cp -f {} ./combined/
          find openwrt/bin/targets/ -name "*combined*img*" | xargs -i cp -f {} ./combined/
          find openwrt/bin/targets/ -name "*config*" | xargs -i cp -f {} ./combined/
          
    - name: Assemble uefi    
      run: |
          rm -rf ./uefi/
          mkdir -p ./uefi/
          find openwrt/bin/targets/ -name "*sysupgrade*bin*" | xargs -i cp -f {} ./uefi/
          find openwrt/bin/targets/ -name "*uefi*img*" | xargs -i cp -f {} ./uefi/
          find openwrt/bin/targets/ -name "*config*" | xargs -i cp -f {} ./uefi/  
    
    - name: Get Date
      run: echo "::set-env name=DATE::$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" 

    - name : Upload combined
      uses: actions/upload-artifact@master
      if: env.UPLOAD_FIRMWARE_COMBINED == 'true'
      with:
        name: ${{env.DATE}} OpenWrt_leo_combined
        path: ./combined/

    - name : Upload uefi
      uses: actions/upload-artifact@master
      if: env.UPLOAD_FIRMWARE_UEFI == 'true'
      with:
        name: ${{env.DATE}} OpenWrt_leo_uefi
        path: ./uefi/
   
    - name: Upload firmware
      uses: actions/upload-artifact@master
      if: env.UPLOAD_FIRMWARE_ALL == 'true'
      with:
        name: ${{env.DATE}} OpenWrt_leo_firmware
        path: ./openwrt/bin/targets/
          
    - name: Upload  IPK
      uses: actions/upload-artifact@master
      if: env.UPLOAD_IPK == 'true'
      with:
        name: ${{env.DATE}} OpenWrt_leo_IPK
        path: ./openwrt/bin/packages/
      
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: '${{env.DATE}} Leo_firmware.zip'
        path: ./openwrt/bin/
    
    - name: Upload firmware to cowtransfer
      if: env.UPLOAD_COWTRANSFER == 'true'
      run: |
        curl -sL https://git.io/cowtransfer | sh
        ./cowtransfer-uploader -s -p 8 ./${{env.DATE}} Leo_firmware.zip
    
    - name: upload to CODING 传到CODING
      continue-on-error : true
      run: |
        git config --global user.email "ycg31@qq.com"
        git config --global user.name "TzePUfjoaA"
        git clone --depth 1 https://TzePUfjoaA:${{ secrets.CODING_TOKEN }}@e.coding.net/ycg31/openwrt_firmware rom
        mkdir -p rom/Lean_master/
        cp -rf ./openwrt/bin/* rom/Lean_master/
        cd rom
        git add . || echo "1"
        git commit -m "github_actions" -a;
        git push